version: '3'

services:
  caddy:
    image: caddy:2.0.0-rc.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/caddy/prod:/etc/caddy
      - ./data:/data
      - ./build:/usr/share/caddy
      - ./uploads:/usr/share/caddy/uploads
    environment:
      SITE_ADDRESS: ${REACT_APP_DOMAIN}
    depends_on:
      - backend
  backend:
    build: .
    ports:
      - 4000
    environment:
      APP_ENV: prod
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - prisma
  prisma:
    build:
      context: .
      dockerfile: config/prisma/Dockerfile
    ports:
      - 4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mariadb
            port: 3306
            user: root
            password: ${DB_PASSWORD}
            database: viator
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.5
    ports:
      - 3306
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=viator
